
webserver:
  image: wordpress

  ports:
    - "55580:80"

  volumes:
    - "$PWD/wordpress:/var/www/html"

  links:
    - "dbserver:mysql"

dbserver:
  image: mysql

  volumes_from:
    - dataonly

  environment:
    MYSQL_ROOT_PASSWORD: password

